### Pandas Masterclass

#### Loading and inspecting

In [67]:
import pandas as pd
import numpy as np

df = pd.read_csv('session_dirty.csv', parse_dates=['timestamp'])

# look at data
print(df.shape) # (rows, columns)
print(df.dtypes) # data types of columns
print(df.describe()) # stats for numeric columns
print(df.isnull().sum())  # null per column

(3001, 10)
timestamp         datetime64[ns]
acc_x                    float64
acc_y                    float64
acc_z                    float64
gyro_x                   float64
gyro_y                   float64
gyro_z                   float64
participant_id            object
session_id                object
activity                  object
dtype: object
                           timestamp        acc_x        acc_y        acc_z  \
count                           3001  2961.000000  2961.000000  3001.000000
mean   2024-03-01 08:59:16.208263936     0.117491    -0.070098     9.850419
min              2024-02-28 08:00:00    -1.520634    -1.638352     8.649003
25%    2024-03-01 09:00:07.489999872    -0.212839    -0.406792     9.594038
50%    2024-03-01 09:00:14.990000128     0.114091    -0.064608     9.797101
75%    2024-03-01 09:00:22.489999872     0.438938     0.269330    10.014420
max       2024-03-01 09:00:29.990000     2.063119     1.571546    19.600000
std                              NaN     0.492789     0.504331     0.756289

            gyro_x       gyro_y       gyro_z
count  3001.000000  3001.000000  3001.000000
mean     -0.000423     0.000681     0.000374
min      -0.078448    -0.066590    -0.072704
25%      -0.013438    -0.012963    -0.013343
50%      -0.000468     0.000732     0.000583
75%       0.012652     0.014096     0.014142
max       0.067555     0.068578     0.089582
std       0.019666     0.020051     0.020138
timestamp          0
acc_x             40
acc_y             40
acc_z              0
gyro_x             0
gyro_y             0
gyro_z             0
participant_id     0
session_id         0
activity          50
dtype: int64

In [68]:
df.head(10)

,timestamp,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,participant_id,session_id,activity
0,2024-03-01 09:00:00.000,0.348357,-1.003904,9.465776,0.015308,0.023496,-0.002868,P002,S002,walking
1,2024-03-01 09:00:00.010,0.030868,-0.480193,9.610721,0.021468,-0.037580,-0.000653,P002,S002,walking
2,2024-03-01 09:00:00.020,0.423844,-0.256803,9.517382,0.009974,-0.006556,0.001286,P002,S002,walking
3,2024-03-01 09:00:00.030,0.861515,0.893844,9.635601,-0.038850,-0.000833,0.018937,P002,S002,walking
4,2024-03-01 09:00:00.040,-0.017077,0.228277,9.735755,-0.003108,0.000318,-0.014944,P002,S002,walking
5,2024-03-01 09:00:00.050,-0.017068,-0.717741,10.051146,-0.023114,0.003610,-0.016927,P002,S002,walking
6,2024-03-01 09:00:00.060,0.889606,0.193018,9.703652,-0.004052,0.012209,0.024732,P002,S002,walking
7,2024-03-01 09:00:00.070,0.483717,-0.823652,9.324312,0.019600,-0.000708,-0.009253,P002,S002,walking
8,2024-03-01 09:00:00.080,-0.134737,0.491346,10.142020,0.006103,-0.007361,-0.025261,P002,S002,walking
9,2024-03-01 09:00:00.090,0.371280,-0.285562,9.548873,0.022962,-0.008152,-0.009703,P002,S002,walking

In [69]:
print(df['activity'].value_counts())

activity
walking     881
running     789
sitting     686
standing    595
Name: count, dtype: int64

#### Filtering and Selection

In [70]:
walkers = df[df['activity'] == 'walking']
print(walkers.shape)

(881, 10)

In [71]:
high_acc = df[(df['acc_z'].abs() > 15) & (df['activity'].notna())]
print(high_acc)

                   timestamp     acc_x     acc_y  acc_z    gyro_x    gyro_y  \
110  2024-03-01 09:00:01.100 -0.859386 -0.630892   19.6  0.036962  0.009835
129  2024-03-01 09:00:01.290 -0.151738 -0.255747   19.6  0.019888 -0.010475
142  2024-03-01 09:00:01.420 -0.703742 -0.099547   19.6  0.004978  0.007347
262  2024-03-01 09:00:02.620 -1.520634 -0.502307   19.6  0.012221  0.022241
581  2024-03-01 09:00:05.810 -0.107644  0.615670   19.6 -0.028184 -0.007826
829  2024-03-01 09:00:08.290 -0.040892  0.190454   19.6 -0.013063 -0.022003
1062 2024-03-01 09:00:10.620  0.674383 -0.525455   19.6  0.017712  0.009289
1241 2024-03-01 09:00:12.410 -0.001790  0.396034   19.6 -0.012925 -0.015535
1630 2024-03-01 09:00:16.300  0.342366 -0.822469   19.6  0.024299 -0.014960
2050 2024-03-01 09:00:20.500  0.512549  0.314532   19.6  0.028887  0.005725
2121 2024-03-01 09:00:21.210  0.492302 -0.268078   19.6  0.001092 -0.005871
2220 2024-03-01 09:00:22.200 -0.079170  0.842388   19.6 -0.018461  0.015973
2292 2024-03-01 09:00:22.920  0.142659 -0.798079   19.6  0.023544 -0.017000
2407 2024-03-01 09:00:24.070  0.514866  0.525134   19.6  0.030413 -0.025612
2861 2024-03-01 09:00:28.610  0.341938  0.564015   19.6 -0.020306 -0.007445

        gyro_z participant_id session_id  activity
110   0.036366           P002       S002   walking
129  -0.031238           P002       S002   walking
142  -0.034461           P002       S002   walking
262   0.024298           P002       S002   walking
581   0.005472           P002       S002   walking
829  -0.006165           P002       S002   walking
1062  0.033701           P002       S002   sitting
1241 -0.002096           P002       S002   sitting
1630  0.005796           P002       S002   running
2050 -0.011736           P002       S002   running
2121 -0.011435           P002       S002   running
2220  0.026116           P002       S002   running
2292  0.009034           P002       S002   running
2407  0.001696           P002       S002  standing
2861 -0.004882           P002       S002  standing

In [72]:
# select cols
sensor_cols = ['acc_x', 'acc_y', 'acc_z']
df[sensor_cols]
print(df[sensor_cols])

         acc_x     acc_y      acc_z
0     0.348357 -1.003904   9.465776
1     0.030868 -0.480193   9.610721
2     0.423844 -0.256803   9.517382
3     0.861515  0.893844   9.635601
4    -0.017077  0.228277   9.735755
...        ...       ...        ...
2996  0.228876  0.526324  10.150165
2997 -0.520880 -0.658702  10.276534
2998  0.267088  0.183975   9.594504
2999  0.022370 -0.635140  10.040355
3000 -0.607685 -0.403446   9.623643

[3001 rows x 3 columns]

In [73]:
# isin - filter by list of values
subset = df[df['participant_id'].isin(['P002'])]
print(subset)

                   timestamp     acc_x     acc_y      acc_z    gyro_x  \
0    2024-03-01 09:00:00.000  0.348357 -1.003904   9.465776  0.015308
1    2024-03-01 09:00:00.010  0.030868 -0.480193   9.610721  0.021468
2    2024-03-01 09:00:00.020  0.423844 -0.256803   9.517382  0.009974
3    2024-03-01 09:00:00.030  0.861515  0.893844   9.635601 -0.038850
4    2024-03-01 09:00:00.040 -0.017077  0.228277   9.735755 -0.003108
...                      ...       ...       ...        ...       ...
2996 2024-03-01 09:00:29.960  0.228876  0.526324  10.150165 -0.001456
2997 2024-03-01 09:00:29.970 -0.520880 -0.658702  10.276534  0.016760
2998 2024-03-01 09:00:29.980  0.267088  0.183975   9.594504 -0.002014
2999 2024-03-01 09:00:29.990  0.022370 -0.635140  10.040355 -0.018926
3000 2024-03-01 09:00:01.000 -0.607685 -0.403446   9.623643 -0.006822

        gyro_y    gyro_z participant_id session_id  activity
0     0.023496 -0.002868           P002       S002   walking
1    -0.037580 -0.000653           P002       S002   walking
2    -0.006556  0.001286           P002       S002   walking
3    -0.000833  0.018937           P002       S002   walking
4     0.000318 -0.014944           P002       S002   walking
...        ...       ...            ...        ...       ...
2996  0.024743 -0.015666           P002       S002  standing
2997  0.026244  0.015705           P002       S002  standing
2998 -0.017682 -0.022986           P002       S002  standing
2999 -0.003076  0.020628           P002       S002  standing
3000 -0.032706  0.029460           P002       S002   walking

[3001 rows x 10 columns]

In [74]:
# Query string cleaner
df.query('acc_z > 15 and activity == "walking"')

,timestamp,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,participant_id,session_id,activity
110,2024-03-01 09:00:01.100,-0.859386,-0.630892,19.6,0.036962,0.009835,0.036366,P002,S002,walking
129,2024-03-01 09:00:01.290,-0.151738,-0.255747,19.6,0.019888,-0.010475,-0.031238,P002,S002,walking
142,2024-03-01 09:00:01.420,-0.703742,-0.099547,19.6,0.004978,0.007347,-0.034461,P002,S002,walking
262,2024-03-01 09:00:02.620,-1.520634,-0.502307,19.6,0.012221,0.022241,0.024298,P002,S002,walking
581,2024-03-01 09:00:05.810,-0.107644,0.615670,19.6,-0.028184,-0.007826,0.005472,P002,S002,walking
829,2024-03-01 09:00:08.290,-0.040892,0.190454,19.6,-0.013063,-0.022003,-0.006165,P002,S002,walking

#### Derived Columns - Vectorise not iterrows

In [75]:
# Accelerometer magnitude
df['acc_magnitude'] = np.sqrt(df['acc_x']**2 + df['acc_y']**2 + df['acc_z']**2)
print(df['acc_magnitude'])

0        9.525234
1        9.622759
2        9.530275
3        9.715245
4        9.738446
          ...
2996    10.166379
2997    10.310788
2998     9.599984
2999    10.060448
3000     9.651246
Name: acc_magnitude, Length: 3001, dtype: float64

In [76]:
# Gyro magnitude
df['gyro_magnitude'] = np.sqrt(df['gyro_x']**2 + df['gyro_y']**2 + df['gyro_z']**2)
print(df['gyro_magnitude'])

0       0.028189
1       0.043284
2       0.012005
3       0.043228
4       0.015268
          ...
2996    0.029322
2997    0.034876
2998    0.029070
2999    0.028164
3000    0.044543
Name: gyro_magnitude, Length: 3001, dtype: float64

In [77]:
# Boolean flag column
df['is_clipped'] = df['acc_z'].abs() > 16.0 # sensor saturation threshold
# print(df['is_clipped'])
print(df['is_clipped'].value_counts()) # check total values
print(df['is_clipped'].sum()) # get only true value counts

is_clipped
False    2986
True       15
Name: count, dtype: int64
15

In [78]:
# np.where - conditional column
df['motion_class'] = np.where(df['acc_magnitude'] > 2.0, 'high_motion', 'low_motion')
print(df['motion_class'])
print(df['motion_class'].value_counts())

0       high_motion
1       high_motion
2       high_motion
3       high_motion
4       high_motion
           ...
2996    high_motion
2997    high_motion
2998    high_motion
2999    high_motion
3000    high_motion
Name: motion_class, Length: 3001, dtype: object
motion_class
high_motion    2921
low_motion       80
Name: count, dtype: int64

In [79]:
# why not iterrows
for idx, row in df.iterrows():
    df.loc[idx, 'mag'] = (row.acc_x**2 + row.acc_y**2 + row.acc_z**2)**0.5
print(df['mag'])

# same result
df['acc_magnitude'] = np.sqrt(df['acc_x']**2 + df['acc_y']**2 + df['acc_z']**2)
print(df['acc_magnitude'])

0        9.525234
1        9.622759
2        9.530275
3        9.715245
4        9.738446
          ...
2996    10.166379
2997    10.310788
2998     9.599984
2999    10.060448
3000     9.651246
Name: mag, Length: 3001, dtype: float64
0        9.525234
1        9.622759
2        9.530275
3        9.715245
4        9.738446
          ...
2996    10.166379
2997    10.310788
2998     9.599984
2999    10.060448
3000     9.651246
Name: acc_magnitude, Length: 3001, dtype: float64

#### GroupBy & Aggregation

In [80]:
# single aggregation
df.groupby('activity')['acc_magnitude'].mean()

activity
running     9.897298
sitting     9.854391
standing    9.869306
walking     9.883966
Name: acc_magnitude, dtype: float64

In [81]:
# multiple aggregations
summary = df.groupby('activity').agg(
    n_rows = ('acc_x', 'count'),
    acc_mean = ('acc_magnitude', 'mean'),
    acc_std = ('acc_magnitude', 'std'),
    gyro_mean = ('gyro_magnitude', 'mean'),
).reset_index()
print(summary)

   activity  n_rows  acc_mean   acc_std  gyro_mean
0   running     776  9.897298  0.848081   0.031665
1   sitting     680  9.854391  0.619759   0.032104
2  standing     584  9.869306  0.646712   0.032472
3   walking     871  9.883966  0.872103   0.031344

In [82]:
# per participant session count
df.groupby('participant_id')['session_id'].nunique().reset_index(name='n_sessions')

  participant_id  n_sessions
0           P002           1

In [83]:
# class distribution per participant - normailised
dist = df.groupby(['participant_id', 'activity']).size().unstack(fill_value=0)
print(dist)
dist_pct = dist.div(dist.sum(axis=1), axis=0).round(3)
print(dist_pct)

activity        running  sitting  standing  walking
participant_id
P002                789      686       595      881
activity        running  sitting  standing  walking
participant_id
P002              0.267    0.232     0.202    0.299

#### Time Series Operations - Critical for Sensor Data

In [84]:
# Parse timestamps if not already datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])
print(df['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)
print(df)

0      2024-03-01 09:00:00.000
1      2024-03-01 09:00:00.010
2      2024-03-01 09:00:00.020
3      2024-03-01 09:00:00.030
4      2024-03-01 09:00:00.040
                 ...
2996   2024-03-01 09:00:29.960
2997   2024-03-01 09:00:29.970
2998   2024-03-01 09:00:29.980
2999   2024-03-01 09:00:29.990
3000   2024-03-01 09:00:01.000
Name: timestamp, Length: 3001, dtype: datetime64[ns]
                   timestamp     acc_x     acc_y      acc_z    gyro_x  \
0    2024-02-28 08:00:00.000  0.563089  0.540320  10.168182 -0.005355
1    2024-03-01 09:00:00.000  0.348357 -1.003904   9.465776  0.015308
2    2024-03-01 09:00:00.010  0.030868 -0.480193   9.610721  0.021468
3    2024-03-01 09:00:00.020  0.423844 -0.256803   9.517382  0.009974
4    2024-03-01 09:00:00.030  0.861515  0.893844   9.635601 -0.038850
...                      ...       ...       ...        ...       ...
2996 2024-03-01 09:00:29.950  0.138740  0.035735   9.830489 -0.023624
2997 2024-03-01 09:00:29.960  0.228876  0.526324  10.150165 -0.001456
2998 2024-03-01 09:00:29.970 -0.520880 -0.658702  10.276534  0.016760
2999 2024-03-01 09:00:29.980  0.267088  0.183975   9.594504 -0.002014
3000 2024-03-01 09:00:29.990  0.022370 -0.635140  10.040355 -0.018926

        gyro_y    gyro_z participant_id session_id  activity  acc_magnitude  \
0     0.010215 -0.001731           P002       S002   walking      10.198085
1     0.023496 -0.002868           P002       S002   walking       9.525234
2    -0.037580 -0.000653           P002       S002   walking       9.622759
3    -0.006556  0.001286           P002       S002   walking       9.530275
4    -0.000833  0.018937           P002       S002   walking       9.715245
...        ...       ...            ...        ...       ...            ...
2996 -0.018193  0.019699           P002       S002  standing       9.831533
2997  0.024743 -0.015666           P002       S002  standing      10.166379
2998  0.026244  0.015705           P002       S002  standing      10.310788
2999 -0.017682 -0.022986           P002       S002  standing       9.599984
3000 -0.003076  0.020628           P002       S002  standing      10.060448

      gyro_magnitude  is_clipped motion_class        mag
0           0.011663       False  high_motion  10.198085
1           0.028189       False  high_motion   9.525234
2           0.043284       False  high_motion   9.622759
3           0.012005       False  high_motion   9.530275
4           0.043228       False  high_motion   9.715245
...              ...         ...          ...        ...
2996        0.035737       False  high_motion   9.831533
2997        0.029322       False  high_motion  10.166379
2998        0.034876       False  high_motion  10.310788
2999        0.029070       False  high_motion   9.599984
3000        0.028164       False  high_motion  10.060448

[3001 rows x 15 columns]

In [85]:
# check monotonicity - non monotonicity = sensor bug/ data corruption
is_monotonic = df['timestamp'].is_monotonic_increasing
print(is_monotonic)
if not is_monotonic:
    bad_rows = df[df['timestamp'] < df['timestamp'].shift(1)]
    print(f'Non-monotonic timestamps at rows: {bad_rows.index.tolist()}')

True

In [86]:
# timestamps diffs - detect gaps
df['ts_diff_ms'] =  df['timestamp'].diff().dt.total_seconds() * 1000
print(df['ts_diff_ms'])
expected_ms = 10 # 100Hz = 10ms between samples
gaps = df[df['ts_diff_ms'] > expected_ms * 3]
print(gaps)

0               NaN
1       176400000.0
2              10.0
3              10.0
4              10.0
           ...
2996           10.0
2997           10.0
2998           10.0
2999           10.0
3000           10.0
Name: ts_diff_ms, Length: 3001, dtype: float64
            timestamp     acc_x     acc_y     acc_z    gyro_x    gyro_y  \
1 2024-03-01 09:00:00  0.348357 -1.003904  9.465776  0.015308  0.023496

     gyro_z participant_id session_id activity  acc_magnitude  gyro_magnitude  \
1 -0.002868           P002       S002  walking       9.525234        0.028189

   is_clipped motion_class       mag   ts_diff_ms
1       False  high_motion  9.525234  176400000.0

In [87]:
# rolling stats (window stats)
df['acc_mag_rolling_mean'] = df['acc_magnitude'].rolling(window=50, min_periods = 1).mean()
print(df['acc_mag_rolling_mean'])
df['acc_mag_rolling_std'] = df['acc_magnitude'].rolling(window=50, min_periods = 1).std()
print(df['acc_mag_rolling_std'])

0       10.198085
1        9.861660
2        9.782026
3        9.719088
4        9.718320
          ...
2996     9.851191
2997     9.859915
2998     9.867055
2999     9.859989
3000     9.860721
Name: acc_mag_rolling_mean, Length: 3001, dtype: float64
0            NaN
1       0.475778
2       0.363602
3       0.322463
4       0.279266
          ...
2996    0.255493
2997    0.259006
2998    0.266662
2999    0.269193
3000    0.269699
Name: acc_mag_rolling_std, Length: 3001, dtype: float64

In [88]:
# resample (reduce sampling rate)
df_indexed = df.set_index('timestamp')
df_25hz = df_indexed[['acc_x', 'acc_y', 'acc_z']].resample('40ms').mean()
print(df_25hz)

                            acc_x     acc_y      acc_z
timestamp
2024-02-28 08:00:00.000  0.563089  0.540320  10.168182
2024-02-28 08:00:00.040       NaN       NaN        NaN
2024-02-28 08:00:00.080       NaN       NaN        NaN
2024-02-28 08:00:00.120       NaN       NaN        NaN
2024-02-28 08:00:00.160       NaN       NaN        NaN
...                           ...       ...        ...
2024-03-01 09:00:29.800  0.419699  0.326137   9.934216
2024-03-01 09:00:29.840 -0.230534 -0.016867   9.811163
2024-03-01 09:00:29.880  0.524998  0.060639  10.067936
2024-03-01 09:00:29.920 -0.026826  0.019435   9.658578
2024-03-01 09:00:29.960 -0.000636 -0.145886  10.015389

[4410750 rows x 3 columns]

#### Merging & Joining

In [101]:
# Left join - keep all rows from seesions, add metadata where available
# print(df.head(5))
df_sessions = df[['session_id']] 
df_metadata = df[['session_id', 'timestamp', 'acc_x', 'acc_y', 'acc_z', 'participant_id', 'activity']]
merged = pd.merge(df_sessions, df_metadata, on='session_id', how='left')
print(merged.head(5))

  session_id               timestamp     acc_x     acc_y      acc_z  \
0       S002 2024-02-28 08:00:00.000  0.563089  0.540320  10.168182
1       S002 2024-03-01 09:00:00.000  0.348357 -1.003904   9.465776
2       S002 2024-03-01 09:00:00.010  0.030868 -0.480193   9.610721
3       S002 2024-03-01 09:00:00.020  0.423844 -0.256803   9.517382
4       S002 2024-03-01 09:00:00.030  0.861515  0.893844   9.635601

  participant_id activity
0           P002  walking
1           P002  walking
2           P002  walking
3           P002  walking
4           P002  walking

In [104]:
# Check for merge failures (right side had no match)
print(merged.columns.tolist())
unmatched = merged[merged['participant_id'].isna()]
print(f'{len(unmatched)} sessions with no metadata match')

['session_id', 'timestamp', 'acc_x', 'acc_y', 'acc_z', 'participant_id', 'activity']
0 sessions with no metadata match

In [107]:
# Concat multiple dataframes (eg combining all session CSVs)
import glob
all_session_dfs = []
for path in glob.glob('./*.csv'):
    tmp = pd.read_csv(path)
    tmp['source_file'] = path
    all_session_dfs.append(tmp)
combined = pd.concat(all_session_dfs, ignore_index=True)
print(combined)

                     timestamp     acc_x     acc_y      acc_z    gyro_x  \
0      2024-03-01 00:00:00.000  0.227085  1.657859   9.419419  0.005097
1      2024-03-01 00:00:00.010 -0.670293 -0.384502  10.336083 -0.071062
2      2024-03-01 00:00:00.020 -0.629743  0.918992   9.363223 -0.032266
3      2024-03-01 00:00:00.030  0.879310 -0.175483   9.444375 -0.094363
4      2024-03-01 00:00:00.040 -0.305767 -1.671521   9.334394  0.008995
...                        ...       ...       ...        ...       ...
52043  2024-03-01 09:00:29.960  0.228876  0.526324  10.150165 -0.001456
52044  2024-03-01 09:00:29.970 -0.520880 -0.658702  10.276534  0.016760
52045  2024-03-01 09:00:29.980  0.267088  0.183975   9.594504 -0.002014
52046  2024-03-01 09:00:29.990  0.022370 -0.635140  10.040355 -0.018926
52047  2024-03-01 09:00:01.000 -0.607685 -0.403446   9.623643 -0.006822

         gyro_y    gyro_z participant_id session_id  activity   site  \
0     -0.028929  0.029229           P001   P001_S01   walking  Tokyo
1      0.074664 -0.051541           P001   P001_S01   walking  Tokyo
2     -0.036712 -0.034317           P001   P001_S01   walking  Tokyo
3      0.122520 -0.026245           P001   P001_S01   walking  Tokyo
4      0.048315  0.057444           P001   P001_S01   walking  Tokyo
...         ...       ...            ...        ...       ...    ...
52043  0.024743 -0.015666           P002       S002  standing    NaN
52044  0.026244  0.015705           P002       S002  standing    NaN
52045 -0.017682 -0.022986           P002       S002  standing    NaN
52046 -0.003076  0.020628           P002       S002  standing    NaN
52047 -0.032706  0.029460           P002       S002   walking    NaN

                           source_file  ppg  heart_rate_bpm
0      ./campaign_multiparticipant.csv  NaN             NaN
1      ./campaign_multiparticipant.csv  NaN             NaN
2      ./campaign_multiparticipant.csv  NaN             NaN
3      ./campaign_multiparticipant.csv  NaN             NaN
4      ./campaign_multiparticipant.csv  NaN             NaN
...                                ...  ...             ...
52043              ./session_dirty.csv  NaN             NaN
52044              ./session_dirty.csv  NaN             NaN
52045              ./session_dirty.csv  NaN             NaN
52046              ./session_dirty.csv  NaN             NaN
52047              ./session_dirty.csv  NaN             NaN

[52048 rows x 14 columns]

#### Handling Missing Values

In [110]:
# Null rate per column
null_rates = df.isnull().mean()
print(null_rates)
problematic = null_rates[null_rates != 0]
print(problematic)

timestamp               0.000000
acc_x                   0.013329
acc_y                   0.013329
acc_z                   0.000000
gyro_x                  0.000000
gyro_y                  0.000000
gyro_z                  0.000000
participant_id          0.000000
session_id              0.000000
activity                0.016661
acc_magnitude           0.026658
gyro_magnitude          0.000000
is_clipped              0.000000
motion_class            0.000000
mag                     0.026658
ts_diff_ms              0.000333
acc_mag_rolling_mean    0.000000
acc_mag_rolling_std     0.000333
dtype: float64
acc_x                  0.013329
acc_y                  0.013329
activity               0.016661
acc_magnitude          0.026658
mag                    0.026658
ts_diff_ms             0.000333
acc_mag_rolling_std    0.000333
dtype: float64

In [111]:
# Drop rows with any null in key sensor columns
df_clean = df.dropna(subset=['acc_x', 'acc_y', 'acc_z'])
df_clean.shape

(2921, 18)

In [114]:
# forward fill (carry last known value) - OK for slow changing signals
df['activity'] = df['activity'].ffill()
print(df.isnull().mean())

timestamp               0.000000
acc_x                   0.013329
acc_y                   0.013329
acc_z                   0.000000
gyro_x                  0.000000
gyro_y                  0.000000
gyro_z                  0.000000
participant_id          0.000000
session_id              0.000000
activity                0.000000
acc_magnitude           0.026658
gyro_magnitude          0.000000
is_clipped              0.000000
motion_class            0.000000
mag                     0.026658
ts_diff_ms              0.000333
acc_mag_rolling_mean    0.000000
acc_mag_rolling_std     0.000333
dtype: float64